#!/bin/bash

if [[ $# < 1 ]]; then
    echo "merges CSV files, retaining only the header from the first file"
    echo "usage: csv_merge merged_filename.csv csv_1 csv_2 ..."
    exit 0
fi

cat $2 > $1
           
for filename in "${*:3}"; do 
    tail -q -n +2 $filename  >> $1 
done

