#!/bin/bash

prlctl start geocoder_ubuntu
ssh geocoder

while true; do
    read -p "Do you wish to shutdown the virtual machine? " yn
    case $yn in
        [Yy]* ) prlctl stop geocoder_ubuntu; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
