#!/usr/bin/Rscript

args <- commandArgs(TRUE)
if(length(args) == 0) {
    cat("knits .md or .Rmd into PDF and HTML documents\nusage: knit file_to_knit.Rmd\n")
    }else rmarkdown::render(args[1], output_format=c('pdf_document','html_document'), quiet 
    = TRUE) 
