#!/usr/local/bin/python

import os, sys, optparse
from smtplib import SMTP

parser = optparse.OptionParser()

parser.add_option('-t', '--to',action='store',dest='to_email',help='destination email',default='NONE!')
parser.add_option('-m', '--message',action='store',dest='email_body',help='email of body',default=' ')

if len(sys.argv)==1:
    parser.print_help()
    sys.exit(1)

options, args = parser.parse_args()


server = SMTP('smtp.gmail.com:587')
server.starttls()
server.login('cole.brokamp@gmail.com','lhlyuprorvzdkuoy')
server.sendmail('cole.brokamp@gmail.com', '%s' % options.to_email, 'Subject: %s' % options.email_body)
server.quit()
