#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ $# < 1 ]]; then
 	echo "converts all WAVs in the current directory to mp3s at 320kbps CBR"
 	echo "adds no metadata to mp3 tag; to do that use max"
 	echo "must specifiy -a to run it"
else
	for f in *.wav; do
	filename="${f%.*}"
	lame --preset insane --noreplaygain -q 2 "${f}" "${filename}.mp3"
	done
fi
