source ~/dotfiles/secrets.sh 2> /dev/null

export VISUAL=vim
export EDITOR="$VISUAL"
export BASH_SILENCE_DEPRECATION_WARNING=1

alias ls='ls -F'
alias ll='ls -o --human-readable --color --group-directories-first'
alias la='ll --all'
alias reload="exec $SHELL -l"
alias path='echo -e ${PATH//:/\\n}'
alias R='R --quiet --no-save'

alias tm='tmux new-session -A -s main'

PROMPT_DIRTRIM=3
PS1="$(tput setaf 33)\u $(tput setaf 244)at $(tput setaf 29)\h $(tput setaf 244)in $(tput setaf 136)\w \n$(tput setaf 244)\$$(tput sgr0) "
PS2="...\$ "

if [ -d /opt/homebrew ]; then
  HOMEBREW_PREFIX=/opt/homebrew
elif [ -d /usr/local/Homebrew ]; then
  HOMEBREW_PREFIX=/usr/local
elif [ -d "$HOME/bin/homebrew" ]; then
  HOMEBREW_PREFIX="$HOME/bin/homebrew"
else
  HOMEBREW_PREFIX=""
fi

if [ -n "$HOMEBREW_PREFIX" ]; then
  eval "$($HOMEBREW_PREFIX/bin/brew shellenv 2>/dev/null)"
  export PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin:$PATH"
  export PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"
  export PATH="$HOMEBREW_PREFIX/opt/grep/libexec/gnubin:$PATH"
  export HOMEBREW_NO_AUTO_UPDATE=1
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add completions for just
if command -v just >/dev/null 2>&1; then
  source <(just --completions bash)
fi

if [ -d "$HOME/.cargo/bin" ]; then
. "$HOME/.cargo/env"
fi
