unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g set-clipboard on
set -g set-titles on

bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind t choose-tree

set -g pane-border-style default
set -g pane-active-border-style default
set -g status-position top
set -g status-justify left
set -g status-style 'bg=#282A36'
set -g status-left ''
set -g status-right ''
setw -g window-status-current-style default
setw -g window-status-current-format '#[bold] ▷ #W ◁ '
setw -g window-status-style default
setw -g window-status-format ' #W '
setw -g mode-style default
set -g message-style default
