set autoread

" faster scrolling
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

set cursorline

set noshowmode "don't show mode in cmd line
set wildmenu " enhance command-line completion

" Optimize for fast terminal connections
set ttyfast
set lazyredraw

"This unsets the 'last search pattern' register by hitting return
nnoremap <CR> :noh<CR><CR>

let mapleader = ","
let maplocalleader = ","

hi CursorLine cterm=underline ctermfg=None ctermbg=None
